version: 0.0
os: linux
files:
  - source: ./embedded-team-backend.zip
    destination: /home/ubuntu
  - source: ./build.sh
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: /home/ubuntu/build.sh
      timeout: 300
      runas: ubuntu