version: 0.2
run-as: root
phases:
  build:
    run-as: root
    on-failure: ABORT
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - mv appspec.yml /
      - zip /embedded-team-backend.zip ./*
    finally:
      - mv em
artifacts:
  files:
    - /embedded-team-backend.zip
    - /appspec.yml
  name: artifact-name
  exclude-paths: true