version: 0.2
run-as: root
phases:
  build:
    run-as: root
    on-failure: ABORT
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - mv appspec.yml ../
      - cd ..
    finally:
      - ls -al
      - zip embedded-team-backend.zip ./src/*
artifacts:
  files:
    - ${CODEBUILD_SRC_DIR}/../embedded-team-backend.zip
    - ${CODEBUILD_SRC_DIR}/../appspec.yml
  name: artifact-name
  exclude-paths: excluded paths