version: 0.2
run-as: root
phases:
  build:
    run-as: root
    on-failure: ABORT
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - ls -al
    finally:
      - zip embedded-team-backend.zip ./embedded-team-backend/*
artifacts:
  files:
    - ./embedded-team-backend.zip
  name: artifact-name
  exclude-paths: excluded paths